INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Project A', 'Category 1', 1000, '2021-08-18', '2022-08-18');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Project B', 'Category 2', 2000, '2021-09-18', '2022-09-18');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Project C', 'Category 3', 3000, '2021-10-18', '2022-10-18');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Project D', 'Category 1', 4000, '2021-11-18', '2022-11-18');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Project E', 'Category 2', 5000, '2021-12-18', '2022-12-18');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Project F', 'Category 3', 6000, '2022-01-18', '2023-01-18');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Project G', 'Category 1', 7000, '2022-02-18', '2023-02-18');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Project H', 'Category 2', 8000, '2022-03-18', '2023-03-18');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Project I', 'Category 3', 9000, '2022-04-18', '2023-04-18');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Project J', 'Category 1', 10000, '2022-05-18', '2023-05-18');

INSERT INTO users (name, age) VALUES ('Alex', 25);
INSERT INTO users (name, age) VALUES ('Barry', 26);
INSERT INTO users (name, age) VALUES ('Chelsea', 27);
INSERT INTO users (name, age) VALUES ('Dan', 28);
INSERT INTO users (name, age) VALUES ('Ellie', 29);
INSERT INTO users (name, age) VALUES ('Frank', 30);
INSERT INTO users (name, age) VALUES ('Georgia', 31);
INSERT INTO users (name, age) VALUES ('Heather', 32);
INSERT INTO users (name, age) VALUES ('Ike', 33);
INSERT INTO users (name, age) VALUES ('James', 34);
INSERT INTO users (name, age) VALUES ('Kathy', 35);
INSERT INTO users (name, age) VALUES ('Laura', 36);
INSERT INTO users (name, age) VALUES ('Meredith', 37);
INSERT INTO users (name, age) VALUES ('Nadia', 38);
INSERT INTO users (name, age) VALUES ('Olive', 39);
INSERT INTO users (name, age) VALUES ('Peter', 40);
INSERT INTO users (name, age) VALUES ('Quirrel', 41);
INSERT INTO users (name, age) VALUES ('Robert', 42);
INSERT INTO users (name, age) VALUES ('Sarah', 43);
INSERT INTO users (name, age) VALUES ('Tom', 44);

INSERT INTO pledges (amount, project_id, user_id) VALUES (100, 10, 20);
INSERT INTO pledges (amount, project_id, user_id) VALUES (200, 9, 19);
INSERT INTO pledges (amount, project_id, user_id) VALUES (300, 8, 18);
INSERT INTO pledges (amount, project_id, user_id) VALUES (400, 7, 17);
INSERT INTO pledges (amount, project_id, user_id) VALUES (500, 6, 16);
INSERT INTO pledges (amount, project_id, user_id) VALUES (600, 5, 15);
INSERT INTO pledges (amount, project_id, user_id) VALUES (700, 4, 14);
INSERT INTO pledges (amount, project_id, user_id) VALUES (800, 3, 13);
INSERT INTO pledges (amount, project_id, user_id) VALUES (900, 2, 12);
INSERT INTO pledges (amount, project_id, user_id) VALUES (1000, 1, 11);
INSERT INTO pledges (amount, project_id, user_id) VALUES (900, 1, 10);
INSERT INTO pledges (amount, project_id, user_id) VALUES (800, 2, 9);
INSERT INTO pledges (amount, project_id, user_id) VALUES (700, 3, 8);
INSERT INTO pledges (amount, project_id, user_id) VALUES (600, 4, 7);
INSERT INTO pledges (amount, project_id, user_id) VALUES (500, 5, 6);
INSERT INTO pledges (amount, project_id, user_id) VALUES (400, 6, 5);
INSERT INTO pledges (amount, project_id, user_id) VALUES (300, 7, 4);
INSERT INTO pledges (amount, project_id, user_id) VALUES (200, 8, 3);
INSERT INTO pledges (amount, project_id, user_id) VALUES (100, 9, 2);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10, 10, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (20, 10, 15);
INSERT INTO pledges (amount, project_id, user_id) VALUES (30, 1, 14);
INSERT INTO pledges (amount, project_id, user_id) VALUES (40, 2, 13);
INSERT INTO pledges (amount, project_id, user_id) VALUES (50, 3, 12);
INSERT INTO pledges (amount, project_id, user_id) VALUES (60, 4, 11);
INSERT INTO pledges (amount, project_id, user_id) VALUES (70, 5, 10);
INSERT INTO pledges (amount, project_id, user_id) VALUES (80, 6, 9);
INSERT INTO pledges (amount, project_id, user_id) VALUES (90, 7, 8);
INSERT INTO pledges (amount, project_id, user_id) VALUES (100, 8, 7);
INSERT INTO pledges (amount, project_id, user_id) VALUES (1000, 9, 6);